/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classes.aula1;

public class App {
  

    public static void main(String[] args) {
       App aplicacao = new App();        
        Pessoa P1 = new Pessoa("Joe");
        Piloto PI = new Piloto("Pedro");
        Mecanico MC = new Mecanico("Sergiao");
        Coopiloto CP = new Coopiloto("Max");
    }

}
